version: "3.1"
services:
  goof:
    build: .
    container_name: goof
    environment:
      - DOCKER=1
      - MYSQL_HOST=good-mysql
      - MYSQL_USER=goof
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
    ports:
      - "3001:3001"
      - "9229:9229"
    links:
      - goof-mongo
    depends_on:
      - goof-mongo
      - good-mysql
    secrets:
      - mysql_password
    networks:
      - default
      - database
  goof-mongo:
    container_name: goof-mongo
    image: mongo:3
    ports:
      - "27017:27017"
  good-mysql:
    container_name: goof-mysql
    image: mysql:5
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: acme
      MYSQL_USER: goof
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password
    networks:
      - database

networks:
  default:
  database:
    internal: true

secrets:
  mysql_password:
    environment: MYSQL_PASSWORD
